Repository AY1920S1-CS2103T-T09-1/main, pull requests merged in 2019-10, with the labels that each got.

#19 Update README for v1.1
  README.adoc
Labels: type.Task

#20 Edit ContactUs page to match project
  docs/ContactUs.adoc
Labels: type.Task

#24 Update User Guide
  docs/UserGuide.adoc
Labels: type.Task

#27 Update use cases and glossary of DG
  docs/DeveloperGuide.adoc
Labels: type.Task

#26 update dg for v1.1
  docs/DeveloperGuide.adoc
Labels: type.Task

#35 Add Branch-activity
  src/main/java/seedu/address/model/activity/Activity.java
  src/main/java/seedu/address/model/activity/Location.java
  src/main/java/seedu/address/model/activity/Name.java
Labels: priority.High, type.Epic

#32 Implement day
  src/main/java/seedu/address/model/day/ActivityWithTime.java
  src/main/java/seedu/address/model/day/Day.java
  src/main/java/seedu/address/model/day/TimeSlot.java
  src/main/java/seedu/address/model/day/Timetable.java
  src/main/java/seedu/address/model/day/exceptions/TimeSlotUnavailableException.java
  src/main/java/seedu/address/model/day/time/DurationInHalfHour.java
  src/main/java/seedu/address/model/day/time/TimeInHalfHour.java
  src/main/java/seedu/address/model/day/time/exceptions/NotInIntervalsOf30MinException.java
  src/main/java/seedu/address/model/day/time/exceptions/TimeOutOfBoundsException.java
Labels: priority.High, type.Epic

#69 Modify minor areas of GUI
  src/main/java/seedu/address/ui/ActivityListPanel.java
  src/main/java/seedu/address/ui/ContactListPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/commons/util/AppUtilTest.java
Labels: priority.High, type.Enhancement

#70 Update AddCommandParser for Activity and Day classes
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/day/Day.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: priority.High, type.Epic

#75 morph list command
  src/main/java/seedu/address/logic/commands/ListActivityCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/ListContactCommand.java
  src/main/java/seedu/address/logic/commands/ListDayCommand.java
  src/main/java/seedu/address/logic/parser/ListCommandParser.java
  src/main/java/seedu/address/logic/parser/PlannerParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/Planner.java
  src/main/java/seedu/address/model/ReadOnlyPlanner.java
  src/main/java/seedu/address/model/day/Day.java
  src/main/java/seedu/address/model/day/Itinerary.java
  src/main/java/seedu/address/model/day/exceptions/DayNotFoundException.java
  src/main/java/seedu/address/model/day/exceptions/DuplicateDayException.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/ListContactCommandTest.java
  src/test/java/seedu/address/logic/parser/PlannerParserTest.java
  src/test/java/seedu/address/model/PlannerTest.java
Labels: priority.High, type.Task

#72 Morph Add command
  src/main/java/seedu/address/logic/commands/AddActivityCommand.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/AddContactCommand.java
  src/main/java/seedu/address/logic/commands/AddDayCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/Planner.java
  src/main/java/seedu/address/model/activity/Activity.java
  src/main/java/seedu/address/model/contact/Contact.java
  src/main/java/seedu/address/model/day/Day.java
  src/main/java/seedu/address/model/field/ContactContainsNumberPredicate.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddContactCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddContactCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddContactCommandParserTest.java
  src/test/java/seedu/address/logic/parser/PlannerParserTest.java
  src/test/java/seedu/address/testutil/ContactUtil.java
Labels: priority.High, type.Task

#76 Morph edit command
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/EditActivityCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/EditContactCommand.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditContactCommandTest.java
  src/test/java/seedu/address/logic/commands/EditContactDescriptorTest.java
  src/test/java/seedu/address/logic/parser/EditContactCommandParserTest.java
  src/test/java/seedu/address/logic/parser/PlannerParserTest.java
  src/test/java/seedu/address/testutil/ContactUtil.java
  src/test/java/seedu/address/testutil/EditContactDescriptorBuilder.java
Labels: priority.High, type.Task

#74 morph delete command
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/DeleteActivityCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/DeleteContactCommand.java
  src/main/java/seedu/address/logic/commands/DeleteDayCommand.java
  src/main/java/seedu/address/logic/commands/EditActivityCommand.java
  src/main/java/seedu/address/logic/commands/EditContactCommand.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/DeleteContactCommandTest.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
  src/test/java/seedu/address/logic/parser/PlannerParserTest.java
Labels: priority.High, type.Task

#78 Implement getActivitiesWithTime in Day class
  src/main/java/seedu/address/model/day/Day.java
  src/main/java/seedu/address/model/day/Itinerary.java
  src/main/java/seedu/address/model/day/TimeSlot.java
  src/main/java/seedu/address/model/day/Timetable.java
Labels: type.Task

#79 Implement unschedule
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/UnscheduleActivityCommand.java
  src/main/java/seedu/address/logic/commands/UnscheduleCommand.java
  src/main/java/seedu/address/logic/commands/UnscheduleTimeCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/UnscheduleCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/Planner.java
  src/main/java/seedu/address/model/day/time/TimeInHalfHour.java
  src/test/java/seedu/address/logic/commands/AddContactCommandTest.java
Labels: priority.High, type.Command

#82 Branch schedule command
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/ScheduleActivityCommand.java
  src/main/java/seedu/address/logic/commands/ScheduleCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/PlannerParser.java
  src/main/java/seedu/address/logic/parser/ScheduleCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/day/time/DurationInHalfHour.java
  src/test/java/seedu/address/logic/commands/AddContactCommandTest.java
Labels: priority.High, type.Command

#86 Fix DeleteDayCommand bug
  src/main/java/seedu/address/logic/commands/DeleteDayCommand.java
Labels: type.Bug

#87 Fix contact related command bugs
  src/main/java/seedu/address/logic/commands/EditContactCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/storage/JsonAdaptedContact.java
  src/test/java/seedu/address/logic/parser/AddContactCommandParserTest.java
  src/test/java/seedu/address/storage/JsonAdaptedContactTest.java
Labels: type.Bug

#88 Morph accommodation
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/AddAccommodationCommand.java
  src/main/java/seedu/address/logic/commands/DeleteAccommodationCommand.java
  src/main/java/seedu/address/logic/commands/EditAccommodationCommand.java
  src/main/java/seedu/address/logic/commands/EditActivityCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/model/accommodation/Accommodation.java
Labels: priority.High, type.Command

#90 Fix bug in DurationInHalfHour
  src/main/java/seedu/address/logic/commands/ScheduleActivityCommand.java
  src/main/java/seedu/address/logic/parser/ScheduleCommandParser.java
  src/main/java/seedu/address/model/day/time/DurationInHalfHour.java
Labels: type.Bug

#92 Change Unschedule command format
  src/main/java/seedu/address/logic/commands/UnscheduleActivityCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/UnscheduleCommandParser.java
Labels: type.Task

#93 update activity and accommodation
  src/main/java/seedu/address/logic/commands/AddAccommodationCommand.java
  src/main/java/seedu/address/logic/commands/AddActivityCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/Planner.java
  src/main/java/seedu/address/model/contact/UniqueContactList.java
  src/main/java/seedu/address/model/field/ContactContainsNumberPredicate.java
  src/test/java/seedu/address/logic/commands/AddContactCommandTest.java
Labels: type.Task

#89 Implement init command
  src/main/java/seedu/address/logic/commands/InitCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/InitCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/PlannerParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/Planner.java
  src/main/java/seedu/address/model/ReadOnlyPlanner.java
  src/main/java/seedu/address/model/day/Itinerary.java
  src/test/java/seedu/address/logic/commands/AddContactCommandTest.java
  src/test/java/seedu/address/model/PlannerTest.java
Labels: priority.High, type.Command

#94 implement ItineraryItem wrapper class
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AddAccommodationCommand.java
  src/main/java/seedu/address/logic/commands/AddActivityCommand.java
  src/main/java/seedu/address/logic/commands/DeleteAccommodationCommand.java
  src/main/java/seedu/address/logic/commands/DeleteActivityCommand.java
  src/main/java/seedu/address/logic/commands/EditAccommodationCommand.java
  src/main/java/seedu/address/logic/commands/EditActivityCommand.java
  src/main/java/seedu/address/logic/commands/ScheduleActivityCommand.java
  src/main/java/seedu/address/logic/commands/UnscheduleActivityCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/Planner.java
  src/main/java/seedu/address/model/ReadOnlyPlanner.java
  src/main/java/seedu/address/model/activity/Activity.java
  src/main/java/seedu/address/model/day/ActivityWithTime.java
  src/main/java/seedu/address/model/day/Timetable.java
  src/main/java/seedu/address/model/itineraryitem/ItineraryItem.java
  src/main/java/seedu/address/model/itineraryitem/accommodation/Accommodation.java
  src/main/java/seedu/address/model/itineraryitem/accommodation/UniqueAccommodationList.java
  src/main/java/seedu/address/model/itineraryitem/accommodation/exceptions/AccommodationNotFoundException.java
  src/main/java/seedu/address/model/itineraryitem/accommodation/exceptions/DuplicateAccommodationException.java
  src/main/java/seedu/address/model/itineraryitem/activity/Activity.java
  src/main/java/seedu/address/model/itineraryitem/activity/UniqueActivityList.java
  src/main/java/seedu/address/model/itineraryitem/activity/exceptions/ActivityNotFoundException.java
  src/main/java/seedu/address/model/itineraryitem/activity/exceptions/DuplicateActivityException.java
  src/main/java/seedu/address/ui/AccommodationCardSmall.java
  src/main/java/seedu/address/ui/AccommodationListPanel.java
  src/main/java/seedu/address/ui/ActivityCardSmall.java
  src/main/java/seedu/address/ui/ActivityListPanel.java
  src/main/java/seedu/address/ui/SplitDisplay.java
  src/test/java/seedu/address/logic/commands/AddContactCommandTest.java
  src/test/java/seedu/address/model/PlannerTest.java
Labels: type.Task

#98 Update UI to use Accordion and BorderPane
  src/main/java/seedu/address/commons/util/AppUtil.java
  src/main/java/seedu/address/ui/CentralDisplay.java
  src/main/java/seedu/address/ui/CommandBox.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/ResultDisplay.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/view/CentralDisplay.fxml
  src/main/resources/view/CommandBox.fxml
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/Extensions.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/ResultDisplay.fxml
  src/test/java/seedu/address/commons/util/AppUtilTest.java
Labels: priority.High, type.Enhancement

#111 Fix previously commented tests
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/model/day/Day.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/day/JsonAdaptedDay.java
  src/test/data/JsonContactStorageTest/invalidAndValidDataContact.json
  src/test/data/JsonContactStorageTest/invalidContact.json
  src/test/data/JsonContactStorageTest/notJsonFormatContact.json
  src/test/data/JsonSerializableContactTest/duplicateDataContact.json
  src/test/data/JsonSerializableContactTest/invalidDataContact.json
  src/test/data/JsonSerializableContactTest/typicalContacts.json
  src/test/data/JsonUserPrefsStorageTest/ExtraValuesUserPref.json
  src/test/data/JsonUserPrefsStorageTest/TypicalUserPref.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddContactCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddContactCommandTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteContactCommandTest.java
  src/test/java/seedu/address/logic/commands/EditContactCommandTest.java
  src/test/java/seedu/address/logic/commands/EditContactDescriptorTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/ListContactCommandTest.java
  src/test/java/seedu/address/logic/parser/AddContactCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditContactCommandParserTest.java
  src/test/java/seedu/address/logic/parser/PlannerParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/UserPrefsTest.java
  src/test/java/seedu/address/model/contact/ContactTest.java
  src/test/java/seedu/address/model/contact/UniqueContactListTest.java
  src/test/java/seedu/address/model/field/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/storage/JsonUserPrefsStorageTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
  src/test/java/seedu/address/storage/contact/JsonAdaptedContactTest.java
  src/test/java/seedu/address/storage/contact/JsonContactStorageTest.java
  src/test/java/seedu/address/storage/contact/JsonSerializableContactTest.java
  src/test/java/seedu/address/testutil/PlannerBuilder.java
  src/test/java/seedu/address/testutil/accommodation/AccommodationBuilder.java
  src/test/java/seedu/address/testutil/accommodation/TypicalAccommodations.java
  src/test/java/seedu/address/testutil/activity/ActivityBuilder.java
  src/test/java/seedu/address/testutil/activity/TypicalActivity.java
  src/test/java/seedu/address/testutil/contact/ContactBuilder.java
  src/test/java/seedu/address/testutil/contact/ContactUtil.java
  src/test/java/seedu/address/testutil/contact/EditContactDescriptorBuilder.java
  src/test/java/seedu/address/testutil/contact/TypicalContacts.java
  src/test/java/seedu/address/testutil/day/ActivityWithTimeBuilder.java
  src/test/java/seedu/address/testutil/day/ItineraryUtil.java
  src/test/java/seedu/address/testutil/day/TypicalActivityWithTime.java
  src/test/java/seedu/address/testutil/day/TypicalDays.java
Labels: priority.Medium

#112 Implement Undo-Redo
  src/main/java/seedu/address/logic/CommandHistory.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AddAccommodationCommand.java
  src/main/java/seedu/address/logic/commands/AddActivityCommand.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/AddContactCommand.java
  src/main/java/seedu/address/logic/commands/AddDayCommand.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/DeleteAccommodationCommand.java
  src/main/java/seedu/address/logic/commands/DeleteActivityCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/DeleteContactCommand.java
  src/main/java/seedu/address/logic/commands/DeleteDayCommand.java
  src/main/java/seedu/address/logic/commands/EditAccommodationCommand.java
  src/main/java/seedu/address/logic/commands/EditActivityCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/EditContactCommand.java
  src/main/java/seedu/address/logic/commands/InitCommand.java
  src/main/java/seedu/address/logic/commands/RedoCommand.java
  src/main/java/seedu/address/logic/commands/UndoCommand.java
  src/main/java/seedu/address/logic/commands/UndoableCommand.java
  src/main/java/seedu/address/logic/events/Event.java
  src/main/java/seedu/address/logic/events/EventFactory.java
  src/main/java/seedu/address/logic/events/add/AddAccommodationEvent.java
  src/main/java/seedu/address/logic/events/add/AddActivityEvent.java
  src/main/java/seedu/address/logic/events/add/AddContactEvent.java
  src/main/java/seedu/address/logic/events/add/AddDayEvent.java
  src/main/java/seedu/address/logic/events/add/AddEventFactory.java
  src/main/java/seedu/address/logic/events/clear/ClearCommandEvent.java
  src/main/java/seedu/address/logic/events/delete/DeleteAccommodationEvent.java
  src/main/java/seedu/address/logic/events/delete/DeleteActivityEvent.java
  src/main/java/seedu/address/logic/events/delete/DeleteContactEvent.java
  src/main/java/seedu/address/logic/events/delete/DeleteDayEvent.java
  src/main/java/seedu/address/logic/events/delete/DeleteEventFactory.java
  src/main/java/seedu/address/logic/events/edit/EditAccommodationEvent.java
  src/main/java/seedu/address/logic/events/edit/EditActivityEvent.java
  src/main/java/seedu/address/logic/events/edit/EditContactEvent.java
  src/main/java/seedu/address/logic/events/edit/EditEventFactory.java
  src/main/java/seedu/address/logic/events/exceptions/EventException.java
  src/main/java/seedu/address/logic/parser/PlannerParser.java
  src/main/java/seedu/address/model/AccommodationManager.java
  src/main/java/seedu/address/model/ActivityManager.java
  src/main/java/seedu/address/model/ContactManager.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/contact/UniqueContactList.java
  src/main/java/seedu/address/model/itineraryitem/accommodation/UniqueAccommodationList.java
  src/main/java/seedu/address/model/itineraryitem/activity/UniqueActivityList.java
  src/main/java/seedu/address/ui/CommandBox.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddContactCommandTest.java
Labels: priority.High, type.Command

#117 Implement OptimiseBudgetCommand
  src/main/java/seedu/address/logic/commands/AddActivityCommand.java
  src/main/java/seedu/address/logic/commands/EditActivityCommand.java
  src/main/java/seedu/address/logic/commands/OptimiseBudgetCommand.java
  src/main/java/seedu/address/logic/commands/ScheduleActivityCommand.java
  src/main/java/seedu/address/logic/commands/ScheduleCommand.java
  src/main/java/seedu/address/logic/commands/UnscheduleActivityCommand.java
  src/main/java/seedu/address/logic/commands/UnscheduleCommand.java
  src/main/java/seedu/address/logic/commands/UnscheduleTimeCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/OptimiseBudgetCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/PlannerParser.java
  src/main/java/seedu/address/logic/parser/ScheduleCommandParser.java
  src/main/java/seedu/address/logic/parser/UnscheduleCommandParser.java
  src/main/java/seedu/address/model/Itinerary.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/activity/Activity.java
  src/main/java/seedu/address/model/day/ActivityWithTime.java
  src/main/java/seedu/address/model/day/Day.java
  src/main/java/seedu/address/model/day/Timetable.java
  src/main/java/seedu/address/model/field/Cost.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/activity/JsonAdaptedActivity.java
  src/main/java/seedu/address/ui/CentralDisplay.java
  src/test/java/seedu/address/logic/commands/AddContactCommandTest.java
  src/test/java/seedu/address/testutil/accommodation/AccommodationBuilder.java
  src/test/java/seedu/address/testutil/activity/ActivityBuilder.java
Labels: priority.Medium, type.Story

#123 Morph List Command
  src/main/java/seedu/address/logic/commands/AutoScheduleCommand.java
  src/main/java/seedu/address/logic/commands/ListAccommodationCommand.java
  src/main/java/seedu/address/logic/commands/ListActivityCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/ListContactCommand.java
  src/main/java/seedu/address/logic/commands/ListDayCommand.java
  src/main/java/seedu/address/logic/commands/OptimiseBudgetCommand.java
  src/main/java/seedu/address/logic/commands/result/ResultInformation.java
  src/main/java/seedu/address/logic/parser/ListCommandParser.java
  src/main/java/seedu/address/ui/CentralDisplay.java
  src/test/java/seedu/address/logic/commands/ListContactCommandTest.java
Labels: type.Command

#129 Add exceptions to AutoSchedule
  src/main/java/seedu/address/logic/commands/AddDayCommand.java
  src/main/java/seedu/address/logic/commands/AutoScheduleCommand.java
  src/main/java/seedu/address/logic/commands/ScheduleCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/ScheduleCommandParser.java
  src/main/java/seedu/address/model/activity/NameWithTime.java
  src/main/java/seedu/address/model/tag/TagWithTime.java
Labels: type.Bug

#128 Enhance View Command
  src/main/java/seedu/address/logic/commands/ViewAccommodationCommand.java
  src/main/java/seedu/address/logic/commands/ViewActivityCommand.java
  src/main/java/seedu/address/logic/commands/ViewCommand.java
  src/main/java/seedu/address/logic/commands/ViewContactCommand.java
  src/main/java/seedu/address/logic/parser/ViewCommandParser.java
  src/main/java/seedu/address/ui/CentralDisplay.java
Labels: type.Enhancement
