Repository AY1920S1-CS2103T-T09-1/main, pull requests merged in 2019-11, with the labels that each got.

#138 Enhance view command
  UnscheduleActivitySequenceDiagram.png
  src/main/java/seedu/planner/logic/commands/ViewAccommodationCommand.java
  src/main/java/seedu/planner/logic/commands/ViewActivityCommand.java
  src/main/java/seedu/planner/logic/commands/ViewContactCommand.java
Labels: type.Enhancement

#142 Fix schedule and unschedule not updating UI bug
  src/main/java/seedu/planner/logic/commands/ScheduleCommand.java
  src/main/java/seedu/planner/logic/commands/UnscheduleCommand.java
  src/main/java/seedu/planner/ui/CentralDisplay.java
Labels: severity.Medium, type.Bug

#134 Branch fix bugs in autoschedule
  src/main/java/seedu/planner/logic/commands/AutoScheduleCommand.java
Labels: type.Bug

#191 Set limit on number of days in itinerary to 31
  src/main/java/seedu/planner/logic/commands/AddDayCommand.java
  src/main/java/seedu/planner/logic/parser/ParserUtil.java
  src/main/java/seedu/planner/model/Itinerary.java
  src/main/java/seedu/planner/model/Model.java
  src/main/java/seedu/planner/model/ModelManager.java
  src/main/java/seedu/planner/model/day/Day.java
  src/main/java/seedu/planner/model/day/DayList.java
  src/test/java/seedu/planner/logic/commands/AddContactCommandTest.java
  src/test/java/seedu/planner/logic/commands/CommandTestUtil.java
Labels: severity.Medium, type.Bug

#192 Fix scheduling bug
  src/main/java/seedu/planner/logic/commands/ScheduleCommand.java
  src/main/java/seedu/planner/logic/parser/ParserUtil.java
  src/main/java/seedu/planner/model/activity/Duration.java
Labels: severity.High, type.Bug

#190 Fix OptimiseCommand bug
  src/main/java/seedu/planner/logic/commands/OptimiseCommand.java
  src/main/java/seedu/planner/logic/events/EventFactory.java
  src/main/java/seedu/planner/logic/events/optimise/OptimiseBudgetEvent.java
  src/main/java/seedu/planner/logic/parser/OptimiseBudgetCommandParser.java
  src/main/java/seedu/planner/logic/parser/PlannerParser.java
  src/main/java/seedu/planner/ui/CentralDisplay.java
Labels: type.Bug

#203 Update HashMap to add contact
  src/main/java/seedu/planner/model/ModelManager.java
Labels: type.Bug

#204 Fix bugs
  src/main/java/seedu/planner/model/ModelManager.java
  src/main/java/seedu/planner/model/activity/Activity.java
  src/main/java/seedu/planner/model/day/Day.java
  src/main/java/seedu/planner/model/day/Timetable.java
Labels: type.Bug

#205 Fix edit activity bug
  src/main/java/seedu/planner/model/ModelManager.java
Labels: type.Bug

#207 Allow overflow in agenda
  src/main/java/seedu/planner/logic/commands/AutoScheduleCommand.java
  src/main/java/seedu/planner/logic/commands/InitCommand.java
  src/main/java/seedu/planner/logic/commands/ScheduleCommand.java
  src/main/java/seedu/planner/logic/commands/util/CommandUtil.java
  src/main/java/seedu/planner/logic/events/schedule/UnscheduleEvent.java
  src/main/java/seedu/planner/model/Itinerary.java
  src/main/java/seedu/planner/model/Model.java
  src/main/java/seedu/planner/model/ModelManager.java
  src/main/java/seedu/planner/model/day/ActivityWithTime.java
  src/main/java/seedu/planner/model/day/DayList.java
  src/main/java/seedu/planner/model/day/Timetable.java
  src/main/java/seedu/planner/model/util/SampleDataUtil.java
  src/main/java/seedu/planner/storage/day/JsonAdaptedActivityWithTime.java
  src/main/java/seedu/planner/ui/CentralDisplay.java
  src/test/java/seedu/planner/logic/commands/AddContactCommandTest.java
  src/test/java/seedu/planner/testutil/day/ActivityWithTimeBuilder.java
  src/test/java/seedu/planner/testutil/day/TypicalActivityWithTime.java
Labels: type.Enhancement

#193 Fix autoschedule bugs
  docs/UserGuide.adoc
  src/main/java/seedu/planner/commons/core/Messages.java
  src/main/java/seedu/planner/logic/commands/AutoScheduleCommand.java
  src/main/java/seedu/planner/logic/commands/result/ResultInformation.java
  src/main/java/seedu/planner/logic/commands/util/CommandUtil.java
  src/main/java/seedu/planner/logic/events/schedule/AutoScheduleEvent.java
  src/main/java/seedu/planner/logic/parser/AutoScheduleCommandParser.java
  src/main/java/seedu/planner/logic/parser/ParserUtil.java
  src/main/java/seedu/planner/model/activity/Activity.java
  src/main/java/seedu/planner/model/activity/ActivityWithCount.java
  src/main/java/seedu/planner/model/activity/Duration.java
  src/main/java/seedu/planner/model/activity/NameWithTime.java
  src/main/java/seedu/planner/model/field/NameOrTagWithTime.java
  src/main/java/seedu/planner/model/tag/TagWithTime.java
Labels: type.Bug

#209 Implement itinerary name change according to trip name
  src/main/java/seedu/planner/model/Itinerary.java
  src/main/java/seedu/planner/model/ReadOnlyItinerary.java
  src/main/java/seedu/planner/ui/CentralDisplay.java
  src/main/java/seedu/planner/ui/MainWindow.java
Labels: type.Enhancement

#212 Enhance design of gui
  src/main/java/seedu/planner/model/day/ActivityWithTime.java
  src/main/java/seedu/planner/ui/CentralDisplay.java
  src/main/resources/view/Agenda.css
  src/main/resources/view/DarkTheme.css
Labels: type.Enhancement

#210 Fix view index bug, help not updating bug and itinerary being shown when there are 0 days
  src/main/java/seedu/planner/logic/commands/HelpCommand.java
  src/main/java/seedu/planner/logic/commands/InitCommand.java
  src/main/java/seedu/planner/logic/commands/ViewAccommodationCommand.java
  src/main/java/seedu/planner/logic/commands/ViewActivityCommand.java
  src/main/java/seedu/planner/logic/commands/ViewContactCommand.java
  src/main/java/seedu/planner/logic/commands/ViewHelpCommand.java
  src/main/java/seedu/planner/logic/commands/ViewInfoCommand.java
  src/main/java/seedu/planner/ui/CentralDisplay.java
Labels: type.Bug

#214 Implement Auto Complete
  src/main/java/seedu/planner/logic/autocomplete/AutoCompleteParser.java
  src/main/java/seedu/planner/logic/autocomplete/AutoCompleteSuggester.java
  src/main/java/seedu/planner/logic/autocomplete/AutoCompleteTextField.java
  src/main/java/seedu/planner/logic/autocomplete/CommandInformation.java
  src/main/java/seedu/planner/logic/autocomplete/exceptions/CommandNotFoundException.java
  src/main/java/seedu/planner/logic/autocomplete/exceptions/CommandWordNotFoundException.java
  src/main/java/seedu/planner/logic/autocomplete/exceptions/PreambleNotFoundException.java
  src/main/java/seedu/planner/logic/autocomplete/exceptions/WordNotFoundException.java
  src/main/java/seedu/planner/logic/commands/ClearCommand.java
  src/main/java/seedu/planner/logic/commands/ExitCommand.java
  src/main/java/seedu/planner/logic/commands/HelpCommand.java
  src/main/java/seedu/planner/logic/commands/InitCommand.java
  src/main/java/seedu/planner/logic/commands/OptimiseCommand.java
  src/main/java/seedu/planner/logic/commands/RedoCommand.java
  src/main/java/seedu/planner/logic/commands/UndoCommand.java
  src/main/java/seedu/planner/logic/commands/addcommand/AddAccommodationCommand.java
  src/main/java/seedu/planner/logic/commands/addcommand/AddActivityCommand.java
  src/main/java/seedu/planner/logic/commands/addcommand/AddContactCommand.java
  src/main/java/seedu/planner/logic/commands/addcommand/AddDayCommand.java
  src/main/java/seedu/planner/logic/commands/deletecommand/DeleteAccommodationCommand.java
  src/main/java/seedu/planner/logic/commands/deletecommand/DeleteActivityCommand.java
  src/main/java/seedu/planner/logic/commands/deletecommand/DeleteContactCommand.java
  src/main/java/seedu/planner/logic/commands/deletecommand/DeleteDayCommand.java
  src/main/java/seedu/planner/logic/commands/editcommand/EditAccommodationCommand.java
  src/main/java/seedu/planner/logic/commands/editcommand/EditActivityCommand.java
  src/main/java/seedu/planner/logic/commands/editcommand/EditContactCommand.java
  src/main/java/seedu/planner/logic/commands/listcommand/ListAccommodationCommand.java
  src/main/java/seedu/planner/logic/commands/listcommand/ListActivityCommand.java
  src/main/java/seedu/planner/logic/commands/listcommand/ListContactCommand.java
  src/main/java/seedu/planner/logic/commands/schedulecommand/AutoScheduleCommand.java
  src/main/java/seedu/planner/logic/commands/schedulecommand/ScheduleCommand.java
  src/main/java/seedu/planner/logic/commands/schedulecommand/UnscheduleCommand.java
  src/main/java/seedu/planner/logic/commands/viewcommand/ViewAccommodationCommand.java
  src/main/java/seedu/planner/logic/commands/viewcommand/ViewActivityCommand.java
  src/main/java/seedu/planner/logic/commands/viewcommand/ViewContactCommand.java
  src/main/java/seedu/planner/logic/commands/viewcommand/ViewHelpCommand.java
  src/main/java/seedu/planner/logic/commands/viewcommand/ViewInfoCommand.java
  src/main/java/seedu/planner/logic/commands/viewcommand/ViewItineraryCommand.java
  src/main/java/seedu/planner/logic/parser/CliSyntax.java
  src/main/java/seedu/planner/logic/parser/PlannerParser.java
  src/main/java/seedu/planner/ui/CentralDisplay.java
  src/main/java/seedu/planner/ui/CommandBox.java
  src/main/java/seedu/planner/ui/ContactCardFull.java
  src/main/java/seedu/planner/ui/InfoListPanel.java
  src/main/java/seedu/planner/ui/MainWindow.java
  src/main/java/seedu/planner/ui/PersonListPanel.java
  src/main/java/seedu/planner/ui/SplitDisplay.java
  src/main/java/seedu/planner/ui/cards/AccommodationCardFull.java
  src/main/java/seedu/planner/ui/cards/AccommodationCardSmall.java
  src/main/java/seedu/planner/ui/cards/ActivityCardFull.java
  src/main/java/seedu/planner/ui/cards/ActivityCardSmall.java
  src/main/java/seedu/planner/ui/cards/ContactCardFull.java
  src/main/java/seedu/planner/ui/cards/ContactCardSmall.java
  src/main/java/seedu/planner/ui/cards/HelpCard.java
  src/main/java/seedu/planner/ui/panels/AccommodationListPanel.java
  src/main/java/seedu/planner/ui/panels/ActivityListPanel.java
  src/main/java/seedu/planner/ui/panels/ContactListPanel.java
  src/main/resources/view/CommandBox.fxml
Labels: type.Enhancement

#228 Fix bugs
  src/main/java/seedu/planner/model/ModelManager.java
Labels: type.Bug

#234 Fix bug of allowing same activity to schedule in same timeslot
  src/main/java/seedu/planner/logic/commands/schedulecommand/ScheduleCommand.java
Labels: type.Bug

#236 Add limit to priority
  src/main/java/seedu/planner/logic/parser/ParserUtil.java
  src/main/java/seedu/planner/model/activity/Priority.java
  src/test/java/seedu/planner/logic/commands/CommandTestUtil.java
  src/test/java/seedu/planner/model/activity/ActivityTest.java
  src/test/java/seedu/planner/model/activity/PriorityTest.java
  src/test/java/seedu/planner/model/activity/UniqueActivityListTest.java
  src/test/java/seedu/planner/testutil/activity/TypicalActivity.java
Labels: severity.Medium, type.Bug

#231 Fix bugs
  src/main/java/seedu/planner/logic/commands/editcommand/EditAccommodationCommand.java
  src/main/java/seedu/planner/logic/commands/editcommand/EditActivityCommand.java
  src/main/java/seedu/planner/model/ModelManager.java
  src/main/java/seedu/planner/model/contact/Contact.java
  src/test/java/seedu/planner/model/contact/ContactTest.java
Labels: type.Bug

#230 Fix Undo/Redo Bug
  src/main/java/seedu/planner/logic/LogicManager.java
  src/main/java/seedu/planner/logic/commands/schedulecommand/UnscheduleCommand.java
  src/main/java/seedu/planner/logic/events/EventFactory.java
  src/main/java/seedu/planner/logic/events/schedule/ScheduleEvent.java
  src/main/java/seedu/planner/logic/events/schedule/UnscheduleEvent.java
  src/main/java/seedu/planner/model/day/Day.java
  src/main/java/seedu/planner/model/day/Timetable.java
Labels: priority.High, type.Bug

#241 Limit number of overlapping activities to 5
  src/main/java/seedu/planner/logic/commands/schedulecommand/ScheduleCommand.java
Labels: priority.High

#245 update hashmap to reduce duplicate contacts
  src/main/java/seedu/planner/model/Itinerary.java
  src/main/java/seedu/planner/model/ModelManager.java
  src/main/java/seedu/planner/model/ReadOnlyItinerary.java
  src/main/java/seedu/planner/model/day/Day.java
Labels: type.Bug

#250 fix duplicate contact bug
  src/main/java/seedu/planner/model/ModelManager.java
Labels: type.Bug

#253 fix delete contact bug
  src/main/java/seedu/planner/model/ModelManager.java
Labels: type.Bug

#263 Fix UnscheduleCommand bugs
  src/main/java/seedu/planner/commons/core/Messages.java
  src/main/java/seedu/planner/logic/commands/listcommand/ListDayCommand.java
  src/main/java/seedu/planner/logic/commands/schedulecommand/UnscheduleCommand.java
Labels: type.Bug

#265 update undoclearcommand to update ui
  src/main/java/seedu/planner/logic/commands/system/UndoClearCommand.java
Labels: type.Bug
